pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
           
        }
       stage('Deploy in Staging Environment'){
            steps{
                build job: 'Tomcat_deployment'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Tomcat_prod_deployment'
            }
        }
    }
        
}
