pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
           
        }
    }
      stage('Deploy in Staging Environment'){
            steps{
                build job: 'Tomcat_deployment'

            }
            
        }
        
}
